{
  includes = [
    ./audio.nix
    ./autoaspm.nix
    ./bluetooth.nix
    ./boot.nix
    ./communicators.nix
    ./cpus.nix
    ./dms
    ./documentation.nix
    ./dolphin.nix
    ./fonts.nix
    ./gaming.nix
    ./ghostty.nix
    ./gpus.nix
    ./helix.nix
    ./home.nix
    ./jujutsu.nix
    ./kernel.nix
    ./keyd.nix
    ./kmscon.nix
    ./laptop.nix
    ./ld.nix
    ./librewolf.nix
    ./locale.nix
    ./logging.nix
    ./media.nix
    ./memory.nix
    ./mineral.nix
    ./modern.nix
    ./moor.nix
    ./networking.nix
    ./niri.nix
    ./nix.nix
    ./ntpd-rs.nix
    ./packages.nix
    ./plymouth.nix
    ./qbittorrent.nix
    ./remove-unused.nix
    ./run0.nix
    ./scx.nix
    ./secrets.nix
    ./shell.nix
    ./ssh.nix
    ./storage.nix
    ./theming.nix
    ./user-chtc.nix
    ./use-xdg-dirs.nix
    ./video.nix
    ./virtualisation.nix
    ./xdg-portals.nix
  ];
}
