name: "nix-config statix check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.21.0pre20240214_d857914/install
          extra_nix_config: |
            experimental_features = ca-derivations nix-command flakes
      - run: nix run nixpkgs#statix -- check ./
