name: "Statix"
on:
  push:
  pull_request:

jobs:
  statix:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5
        - uses: samueldr/lix-gha-installer-action@latest
        - name: "Statix"
          run: nix run nixpkgs#statix -- check -i npins
